version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - aws cloudformation package --template-file deploy/template.yaml --kms-key-id $CODE_KEY --s3-bucket $S3_BUCKET --output-template-file templated.yaml
artifacts:
  type: zip
  files:
    - templated.yaml
    - deploy/template_config.json